added essence team documentation
soffan-group-25/ci-server pull request #69
Opened 2023-02-08 19:16 UTC by hebbs4152

## Describe your changes

## Checklist before requesting review

-   [ ] Feature/fix PRs should add one atomic (as small as possible) feature or
        fix
-   [ ] If your PR adds a feature or fix it also needs to add or modify at least
        one test
-   [ ] All code in your PR needs to have been formatted
-   [ ] The merge commit title should follow our commit prefix convention of
        either "feat", "fix", "chore", "doc", or "refactor"
-   [ ] The merge commit body should reference at least one issue
-   [ ] The code compiles and all the tests pass

2023-02-08 19:22 UTC, hebbs4152 commented
solves #18

2023-02-08 22:25 UTC, haval0 requested changes
Covers all the bases, well done

I have two nitpicks:

2023-02-08 22:25 UTC, haval0 commented on README.md
> +## Essence - Way of Working
```suggestion
## Essence - Team
```

2023-02-08 22:25 UTC, haval0 commented on Essence.md
> +When we started the assignment much of the *seeded* state was already completed. The team mission was laid out in the instructions and transferred over to GitHub in the form of issues and requirement
fix typo:
strukture -> structure

2023-02-09 10:06 UTC, danielwis approved these changes

2023-02-09 10:18 UTC, haval0 approved these changes

2023-02-09 10:19 UTC, merged